#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl11, bump1,          sensorNone)
#pragma config(Sensor, dgtl12, bump2,          sensorNone)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************************************************************
*
*  This file is meant as an introduction and as a template for developing
*  programs to run on the Vex controller.
*
*******************************************************************************/

/*******************************************************************************
*
*	main
*
*******************************************************************************/
task main()
{
//  int bumper = 1;	              // normal bumper state = 1; when pressed = 0

  wait1Msec(2000);    					// give stuff time to turn on
	int sensor_value;
  while(true)
  {
    //Joystick control of the motors
        // up = CCW

    //If the bumper is press, automatically backup
		sensor_value = SensorValue(lightSensor);
		motor[leftMotor] = 127 - (127/(float)1023)*sensor_value;
		motor[rightMotor] = -127 + (127/(float)1023)*sensor_value;
		writeDebugStream("%d\n",(127/1023) * (float)sensor_value);
		writeDebugStream("light sensero : %d   motor speed : %d \n",sensor_value,127 - (127/1023)*sensor_value);//print the number

  }
}
