#pragma config(Sensor, in1,    Light_sensor,   sensorReflection)
#pragma config(Sensor, in2,    Potmeter_sensor, sensorPotentiometer)
#pragma config(Sensor, dgtl9,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, LimitSwitch1,   sensorTouch)
#pragma config(Sensor, dgtl12, LimitSwitch2,   sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port8,           Servo,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 50;
void ServoMove(int servoPosition){
  writeDebugStreamLine("Servo Position = %d",servoPosition);
  motor[Servo] = servoPosition;
  wait1Msec(1000);
}
void turnright(){
		motor[leftMotor] = -50;
		motor[rightMotor] = 50;
		wait1Msec(300);
		motor[leftMotor] = 50;  //right turn. extra 10 over cause it get stuckin ther frequenly
		motor[rightMotor] = 50;
		wait1Msec(800);
		}
	void turnleft(){
		wait1Msec(275);
		motor[leftMotor] = -50;  //left turn
		motor[rightMotor] = -50;
		wait1Msec(680);
		motor[leftMotor] = 50;
		motor[rightMotor] = -50;
		wait1Msec(800);
		}

	void slightlyr(){
		/**
		 *then maze runner get too close to the wall, we need to acc left and slow right to turn slightly right
		**/
		motor[leftMotor] = 60;  //right turn
		motor[rightMotor] = -45;
		wait1Msec(35);
	}
	void slightlyl(){
		/**
		 *then maze runner get too far to the wall, we need to acc left and slow right to turn slightly right
		**/
		motor[leftMotor] = 45;  //left turn
		motor[rightMotor] = -60;
		wait1Msec(35);

	}

task main()
{
	int sonar_value;
	while(true){
		motor[leftMotor] = 50;
		motor[rightMotor] = -50;
		sonar_value = SensorValue(sonarSensor);

		if(SensorValue(LimitSwitch1) || SensorValue(LimitSwitch2)) {
			turnright();
			continue;
		}
		if(sonar_value <12){
			slightlyr();
		}
		if(sonar_value >=13 && sonar_value < 35){
			slightlyl();
		}
		if(sonar_value >=35){
			turnleft();
		}

//	//left_switch = SensorValue(LimitSwitch1);
//	//right_switch = SensorValue(LimitSwitch2);
//	sonar_value = SensorValue(sonarSensor);
//	if(SensorValue(LimitSwitch1) == 1 || SensorValue(LimitSwitch2) == 1){
//		turnright();
//		}
//	while (SensorValue(LimitSwitch3) == 1){
//		slightlyl();
//		}
//	while (SensorValue(LimitSwitch4) == 1){
//		slightlyr();
//		}
//	if (sonar_value > 10){
//		turnleft();
//		}


	}
}
